name: HealthyHabitatAI
dependencies:
  - keras
  - matplotlib
  - opencv
  - python=3.6.5
  - Pillow
  - pip
  - shapely
  - pip:
    - albumentations
    - azureml-sdk[notebooks,automl]
    - azure-cognitiveservices-vision-customvision
    - azure-storage
    - azure-functions
    - imgaug
    - imutil
    - python-dotenv
    - segmentation-models