name: HealthyHabitatAI
dependencies:
  - matplotlib
  - python=3.6.5
  - Pillow
  - pip
  - pip:
    - azureml-sdk[notebooks,automl]
    - azure-cognitiveservices-vision-customvision
    - azure-storage
    - azure-functions